### ISSUE TITLE
Restore necrotic/radiant energy tradition for undead/living

### ISSUE THREAD

**Issue by Xehanort88** [BG3-Community-Library-Team/BG3-Community-Library#7]
I have been looking at ways on how to return the feature "radiant harms undead & heals living, necrotic does the opposite".

I have a couple solutions in mind, but wonder what would work best/at all.

1) additional conditions added on each relevant spell, like it was done in NWN, which is definitely doable if time-consuming;

2) a passive added on undead NPCs/PCs by the "character" data file (unknown feasibility);

3) a passive condition added on races, if possible at all, which triggers and should hopefully be displayed in the character/npc sheet, but not as a status. Maybe a feat? unsure on the feasibility on this one.

**Comment by khuckins** [comment]
1. seems like the most feasible - using 
```
IF(Target:IsTagged('UNDEAD')):RegainHitPoints(val);IF(not Target:IsTagged('UNDEAD')):DealDamage(val, Radiant)
```

(Switching around for Necrotic)

This could be problematic with more complex spells, but it's, as far as I'm aware, the only way to retain the value passed in to DealDamage.

If using a passive, I imagine you'd want to be using `Resistance(Necrotic, Immunity` for undead, for example, a StatsFunctorContext of `OnAttacked` with conditions checking if the attack was a hit, and was of the correct type, followed by a RegainHitPoints(context.HitDescription.TotalDamageDone) (Assuming context.HitDescription is useable within the StatsFunctor and isn't set to 0 because of the immunity)

**Comment by Xehanort88** [comment]
Example formula: 

```
data "SpellProperties" "IF(not Tagged('UNDEAD')):RegainHitPoints(1d8+SpellCastingAbilityModifier);IF(Tagged('UNDEAD')):DealDamage(1d8+SpellCastingAbilityModifier,Radiant)"
data "TargetRadius" "1.5"
data "TargetConditions" "Character() and not Dead()"
```

**Comment by TheRealDjmr** [comment]
Yes that is the example I provided for Cure Wounds, the full version of which would therefore be:

`new entry "Target_CureWounds"
type "SpellData"
data "SpellType" "Target"
data "Level" "1"
data "SpellSchool" "Evocation"
data "SpellProperties" "TARGET:IF(not Tagged('UNDEAD')):RegainHitPoints(1d8+SpellCastingAbilityModifier);TARGET:IF(Tagged('UNDEAD')):DealDamage(1d8+SpellCastingAbilityModifier,Radiant)"
data "TargetRadius" "1.5"
data "TargetConditions" "Character() and not Dead()"
...
data "CycleConditions" "Character() and not Dead()"`

However the same change (or similar) would need to be done for all healing/necrotic spells.

I think it would make a good mod in it's own right, but not my cup of tea.
